services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_backend
    volumes:
      - ./back:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=site_db
      - DB_USER=user
      - DB_PASS=userpass
    depends_on:
      - db

  frontend:
    image: node:18
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: site_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init_table.sql:/docker-entrypoint-initdb.d/init_table.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data: